name: 'GitHub Actions LZU Auto COVID Health Report'
    
on:
  workflow_dispatch:  # Allow manual triggers
    inputs:
      delays:
        description: 'Delayed time (Optional) 可选延迟时间'
        required: false
  schedule:
    - cron: '0 23 * 1,2,7,8 *' # Schedule on CST 7 everyday during Jan. Feb. Jul. Aug.

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
        - name: 'Set up Python'
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        - name: 'Install requirements'
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Time wait ${{ github.event.inputs.delays }}
          if: ${{ github.event.inputs.delays != '' }}
          run: sleep ${{ github.event.inputs.delays }}
        - name: 'Auto COVID Health Report'
          env:
            CARDID: ${{ secrets.CARDID }}
            PASSWORD: ${{ secrets.PASSWORD }}
            TZ: Asia/Shanghai
          run: python LZU-Auto-COVID-Health-Report.py >> information.txt && cat information.txt
        - name: 'Error logging and Notifying'
          env:
            SERVERCHANSCKEY: ${{ secrets.SERVERCHANSCKEY }}
            OPENID: ${{ secrets.OPENID }}
            PPTOKEN: ${{ secrets.PPTOKEN }}
            PPTOPIC: ${{ secrets.PPTOPIC }}
            TGBOTTOKEN: ${{ secrets.TGBOTTOKEN }}
            TGCHATID: ${{ secrets.TGCHATID }}
          if: ${{ failure() }}
          run: python Notify-Result.py failure && cat information.txt
        - name: 'Notify Success'
          env:
            SERVERCHANSCKEY: ${{ secrets.SERVERCHANSCKEY }}
            OPENID: ${{ secrets.OPENID }}
            PPTOKEN: ${{ secrets.PPTOKEN }}
            PPTOPIC: ${{ secrets.PPTOPIC }}
            TGBOTTOKEN: ${{ secrets.TGBOTTOKEN }}
            TGCHATID: ${{ secrets.TGCHATID }}
          if: ${{ success() }}
          run: python Notify-Result.py success
        - name: 'Re-run workflow if failed and GPATOKEN set'
          env:
            GPATOKEN: ${{ secrets.GPATOKEN }}
          if: ${{ failure() && (env.GPATOKEN != '') }}
          uses: benc-uk/workflow-dispatch@v1
          with:
            workflow: 'GitHub Actions LZU Auto COVID Health Report'
            token: ${{ secrets.GPATOKEN }}
            inputs: '{ "delays": "10m" }'
